version: 2

services:
  web:
    source: .
    build:
      builder: nixpacks
      buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    deploy:
      startCommand: python app.py
      restartPolicyType: on_failure
      restartPolicyMaxRetries: 10
    variables:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      NIXPACKS_PYTHON_VERSION: "3.11"
    healthcheck:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
